name: "automerge pr"
description: "automatically merge a PR with only one line changed and a comment on the PR"
inputs:
  github-token:
    description: GitHub WebHook Secret Token
    required: true
  filepath:
    description: Path to you'd like to update from root repo
    required: true
  raw-link:
    description: The link to the raw file you'd like to update. ex - 'https://raw.githubusercontent.com/{owner}/{repo}/{defaultbranch}/{filename}' 
    required: true
  file-link:
    description: https://api.github.com/repos/{owner}/{repo}/contents/{filename}
  email:
    description: Email for commits
    required: true
runs:
  using: "node12"
  main: "./index.js"
branding:
  icon: "git-merge"
  color: "orange"