name: "automerge pr"
description: "automatically merge a PR with only one line changed and a comment on the PR"
inputs:
  github-token:
    description: GitHub WebHook Secret Token
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "git-merge"
  color: "orange"