name: "Automatically Merge PR"
description: "Autometically Merge PR using custom PR label/ PR라벨을 이용해 자동으로 머지작업을 해줍니다"
inputs:
  merge-method:
    description: The merge method; merge, squash or rebase.
    required: false
    default: "merge"
  github-token:
    description: GitHub WebHook Secret Token
    required: true
runs:
  using: "node12"
  main: "src/index.js"
branding:
  icon: "git-merge"
  color: "orange"